# Generated by Django 4.2.6 on 2023-10-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="total_cooking_time",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Общее время приготовления (в минутах)"
            ),
        ),
    ]
